---
title: "R24-16S"
author: "Katherine Mueller"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(phyloseq)
library(readr)
library(readxl)
```

Merge ASV count and taxonomy files
```{r}
biom_file <- "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Clinical Isolates/Data/Data_for_analysis/Community_Analysis/second_biom/2020-10-16_update/otu-table.txt"
taxonomy_file <- "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Clinical Isolates/Data/Data_for_analysis/Community_Analysis/second_biom/2020-10-16_update/taxonomy.tsv"

otu_table <- read.table(file = biom_file, header = TRUE)
tax <- read.table(file = taxonomy_file, sep = '\t', header = TRUE)
merged <- merge(otu_table, tax, by.x = c("OTUID"), by.y = c("OTUID"))
head(merged)
write.table(merged, file = "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Clinical Isolates/Data/Data_for_analysis/Community_Analysis/second_biom/2020-10-16_update/combined_otu_tax", sep = '\t', col.names = TRUE, row.names = FALSE)
```

Load files into phyloseq
```{r}
map_file <- "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Clinical Isolates/Data/Data_for_analysis/Community_Analysis/second_biom/sample-metadata.txt"

metadata <- read_delim(map_file, "\t", escape_double = FALSE, trim_ws = TRUE)
```

Import as phyloseq objects
```{r}
OTU <- otu_table(otu_table, taxa_are_rows = TRUE)
meta <- sample_data(metadata)
```

Set up subsets for analysis
```{r}
verruco_percent <- "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Clinical Isolates/Data/Data_for_analysis/Community_Analysis/second_biom/2020-10-16_update/verruco_percent.xlsx"

isolates <- read_excel(verruco_percent)
samples_with_isolates <- isolates$Isolate

isolate_subset <- subset_samples(merged_phyloseq, patient %in% samples_with_isolates)

baseline <- subset_samples(isolate_subset, visit == 1)
endpoint <- subset_samples(isolate_subset, visit == 5)
```

Plot top 20 OTUs and color by family. Provided by Jay.
```{r}

```

