---
title: "Full Set Analysis"
author: "Katherine Mueller"
date: "3/12/2021"
output: html_document
---

##Setup

#Load Libraries
```{r}
library(readr)
library(phyloseq)
library(tibble)
library(dplyr)
library(ggplot2)
library(microbiomeMarker)
```

#Define Paths
```{r}
r24.rds = "../../Data/Data_for_analysis/Community_Analysis/full_R24/phyloseq_r24_complete_16S_metadata_corrected.rds"
out.dir = "../../Data/Data_for_analysis/Community_Analysis/full_R24"
```

#Load and Check Phyloseq Object
```{r}
r24.ps = read_rds(r24.rds)
print(r24.ps)
```

```{r}
sample_variables(r24.ps)
```
##Processing
#Rename Taxa Titles
```{r}
taxa_table <- tax_table(r24.ps) %>%
  as.data.frame() %>%
  rename(Kingdom = domain, Phylum = phylum, Class = class, Order = order, Family = family, Genus = genus, Species = species) %>%
  as.matrix() %>%
  tax_table()
```

#Recreate phyloseq object
```{r}
asvs <- otu_table(r24.ps)
meta <- sample_data(r24.ps)

r24.ps.goodtaxa <- phyloseq(asvs, meta, taxa_table)
print(r24.ps.goodtaxa)
```

#Filter for Patients and Controls
```{r}
people.ps <- r24.ps.goodtaxa %>%
  subset_samples(group %in% c("HWC", "OB"))
print(people.ps)
```

#Convert ASV Counts to Relative Abundance
```{r}
people.ps.rel <- people.ps %>%
  transform_sample_counts(function(x) x / sum(x))
```

```{r}
head(sample_sums(people.ps.rel))
```

##Make Verruco Abundance into Sample Variables
#Calculate Phylum-level Abundance
```{r}
people.ps.rel.verrucos <- people.ps.rel %>%
  subset_taxa(Phylum == "Verrucomicrobiota") %>%
  tax_glom("Phylum")
print(people.ps.rel.verrucos)
```
```{r}
#First/original column is percent verruco
verrucos <- people.ps.rel.verrucos %>%
  otu_table() %>%
  as.data.frame()
names(verrucos)[1] <- "percent"

#Determine +/- Verruco based on a 0.01% cutoff
verrucos <- verrucos %>%
  mutate(has_verruco = ifelse(percent >= 0.0001, 1, 0))
```

#Assign New Variables
```{r}
sample_data(people.ps.rel)$verruco_abund <- verrucos$percent
sample_data(people.ps.rel)$verruco_presence <- verrucos$has_verruco
```

```{r}
sample_variables(people.ps.rel)
```
